services:
  db:
    image: mysql:8.0
    container_name: eyoklama-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ibu_yoklama
      TZ: Europe/Istanbul
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: eyoklama-backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Europe/Istanbul

  frontend:
    build: ./frontend
    container_name: eyoklama-frontend
    expose:
      - "5173"
    depends_on:
      - backend

  admin-panel:
    build: ./admin-panel
    container_name: eyoklama-admin
    ports:
      - "8080:8080"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: eyoklama-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  
     - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data: